# Generated by Django 3.2.3 on 2021-06-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('moodId', models.IntegerField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('songId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('mood1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood1', to='lyrics.mood')),
                ('mood2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood2', to='lyrics.mood')),
                ('mood3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mood3', to='lyrics.mood')),
            ],
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('songId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.songinfo')),
            ],
        ),
    ]
