# Generated by Django 3.2.3 on 2021-06-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='imgURL',
            field=models.URLField(default='https://cdnimg.melon.co.kr/cm2/album/images/100/43/575/10043575_20210302112520_500.jpg/melon/resize/120/quality/80/optimize'),
        ),
    ]
